# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true  # Activer la protection CSRF

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true  # Activer les sessions
        handler_id: null
        cookie_secure: auto  # Utiliser auto pour définir les cookies de session de manière sécurisée
        cookie_samesite: lax  # Recommandé pour la sécurité des cookies

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
